### ISSUE TITLE
Issue with Get Features part

### ISSUE THREAD

**Issue by Ykond** [lmotta/gimpselectionfeature_plugin#11]
Good morning, thanks for an amazing plugin. Im using Qgis 3.18 and when i reach the point to GET FEATURES I get an error message : 

2022-03-17T16:31:09     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.

2022-03-17T16:31:09     WARNING    Traceback (most recent call last):
              File "C:/Users/yazan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gimpselectionfeature_plugin\gimpselectionfeature.py", line 552, in getFeatures
              if not setLayerPolygon() or not self._setConnectionSocket():
              File "C:/Users/yazan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gimpselectionfeature_plugin\gimpselectionfeature.py", line 484, in setLayerPolygon
              r = self._getFirstLayerPolygon()
              File "C:/Users/yazan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gimpselectionfeature_plugin\gimpselectionfeature.py", line 382, in _getFirstLayerPolygon
              layers = [ ltl.layer() for ltl in self.root.findLayers() if ltl.layer().source() == source ]
              File "C:/Users/yazan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gimpselectionfeature_plugin\gimpselectionfeature.py", line 382, in 
              layers = [ ltl.layer() for ltl in self.root.findLayers() if ltl.layer().source() == source ]
             **AttributeError: 'NoneType' object has no attribute 'source'**
             
How can I fix this? Thanks a lot.

**Comment by lmotta** [comment]
Hi Ykond,

The error message is about the return 'NoneType' by "ltl.layer()".

The API document of QGIS have the warning about return this NoneType [1]
"Warning: This can be (and often is!) nullptr, e.g. in the case of a layer node representing a layer which has not yet been fully loaded into a project, or a layer node representing a layer with an invalid data source. The returned pointer must ALWAYS be checked to avoid dereferencing nullptr."

Please check if in your project have "invalid source"

[1] https://api.qgis.org/api/classQgsLayerTreeLayer.html


Source:

**Comment by Ykond** [comment]
Thank you! I deleted the other WMS layers which were on my project even though they didn't work due to the need for an API key or for whatever other reasons and the Plugin worked as it should. 

Thanks again!
